### ISSUE TITLE
Support for multiple agencies

### ISSUE THREAD

**Issue by adrianmo** [artonge/go-gtfs#15]
Currently the library only takes the first agency in the `agency.txt`, and that is OK for most feeds as they typically are single-agency feeds, however, other GTFS feeds contain data for more than one agency in the same feed. For example, the `agency.txt` file in the SNCF feed for *[Horaires des lignes Transilien](https://ressources.data.sncf.com/explore/dataset/sncf-transilien-gtfs/information/)* looks like this:

```
agency_id,agency_name,agency_url,agency_timezone,agency_lang
DUA853,"Paris Nord",http://www.transilien.com,Europe/Paris,fr
DUA854,"Paris St Lazare",http://www.transilien.com,Europe/Paris,fr
DUA852,"Paris Rive Gauche",http://www.transilien.com,Europe/Paris,fr
DUA803,"RER C",http://www.transilien.com,Europe/Paris,fr
DUA804,"RER D",http://www.transilien.com,Europe/Paris,fr
DUA850,"Paris Est",http://www.transilien.com,Europe/Paris,fr
DUA855,"La Verrière - La Défense",http://www.transilien.com,Europe/Paris,fr
DUA851,"Paris Sud Est",http://www.transilien.com,Europe/Paris,fr
DUA805,"RER E",http://www.transilien.com,Europe/Paris,fr
DUA802,"RER B",http://www.transilien.com,Europe/Paris,fr
DUA801,"RER A",http://www.transilien.com,Europe/Paris,fr
```

**Comment by artonge** [comment]
Hello,

Thanks for the feedback !

I am not actively working on this library anymore. But I accept pull requests. Can you make one ?

**Comment by adrianmo** [comment]
Sure, I'll give it a go as soon as I can.
